# Generated by Django 5.2.7 on 2025-10-14 23:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(error_messages={'unique': 'このユーザーIDは既に使用されています'}, help_text='ログインに使用するユニークなID', max_length=30, unique=True, verbose_name='ユーザーID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='名')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='姓')),
                ('is_teacher', models.BooleanField(default=False, help_text='教員の場合はTrue、学生の場合はFalse', verbose_name='教員')),
                ('is_superuser', models.BooleanField(default=False, help_text='管理サイトにログインできるかどうか', verbose_name='スーパーユーザー権限')),
                ('is_active', models.BooleanField(default=True, help_text='このユーザーがアクティブかどうか。アカウント削除の代わりに無効化する場合に使用', verbose_name='有効')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'permissions': [('create_assignment', '課題を作成できる'), ('update_assignment', '課題を更新できる'), ('delete_assignment', '課題を削除できる'), ('check_status', '課題の状態を確認できる')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'verbose_name': '教員',
                'verbose_name_plural': '教員',
                'permissions': [('view_student_progress', '学生の進捗状況を閲覧できる'), ('send_reminders', 'リマインドを送信できる')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
        ),
    ]
