# Generated by Django 5.2.7 on 2025-10-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未提出'), (1, '提出済み'), (2, '受理'), (3, '再提出'), (4, '再提出提出済み')], default=0),
        ),
    ]
