# Generated by Django 5.2.7 on 2025-10-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_assignment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='title',
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_number',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
